steps:

trigger:
 branches:
   include:
     - develop

pr:
 branches:
   include:
     - develop
     
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
